name: mcs-t417
version: 0.0.1
license: BSD3
author: Satoshi Takimoto
maintainer: wasabi.nvim.st@gmail.com
copyright: 2024 Satoshi Takimoto
category: Language

language: GHC2021

default-extensions:
  - BlockArguments
  - DeriveAnyClass
  - DerivingStrategies
  - DerivingVia
  - LambdaCase
  - OverloadedLists
  - OverloadedRecordDot
  - NoFieldSelectors
  - OverloadedStrings
  - PatternSynonyms
  - Strict
  - RecordWildCards
  - TypeFamilies
  - ViewPatterns
  - TemplateHaskell
  - MultiParamTypeClasses
  - FunctionalDependencies
  - GADTs

ghc-options:
  - -Wall
  - -Wno-unused-do-bind
  - -Wmissing-deriving-strategies
  - -O2
  - -funbox-strict-fields

dependencies:
  - base >=4.17 && < 5
  - megaparsec
  - mtl
  - text
  - prettyprinter
  - strict-list
  - unordered-containers
  - hashable
  - mason

library:
  source-dirs: src

executables:
  mcs-t417-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - mcs-t417
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts= "-A64M -s -N8"
